import { useTranslation } from "react-i18next";

const Area = () =>{
    const {t} = useTranslation()
    return <select className="form-control form-select" name="area_id" id="guest_area_id" required>
    <option value="">{t("Please Select")}</option>
    <option value="162">الاندلس</option>
                                                                <option value="163">الرابيه</option>
                                                                <option value="164">الرحاب</option>
                                                                <option value="165">العارضية</option>
                                                                <option value="166">العمرية</option>
                                                                <option value="167">الفردوس</option>
                                                                <option value="168">أبرق خيطان</option>
                                                                <option value="169">جليب الشيوخ</option>
                                                                <option value="170">جنوب خيطان</option>
                                                                <option value="171">الجهراء</option>
                                                                <option value="172">صباح الناصر</option>
                                                                <option value="173">الصليبية</option>
                                                                <option value="174">ضاحية عبدالله المبارك</option>
                                                                <option value="175">العيون</option>
                                                                <option value="176">الضجيج</option>
                                                                <option value="177">القصر</option>
                                                                <option value="178">الشدادية</option>
                                                                <option value="179">النسيم</option>
                                                                <option value="180">العرضية الحرفية</option>
                                                                <option value="181">النعيم</option>
                                                                <option value="182">العارضية 6</option>
                                                                <option value="183">الدوحة</option>
                                                                <option value="184">الواحة</option>
                                                                <option value="185">الفروانية</option>
                                                                <option value="186">تيماء</option>
                                                                <option value="187">سعد العبد الله</option>
                                                                <option value="188">اشبيلية</option>
                                                                <option value="189">منطقة امغرة صناعية</option>
                                                                <option value="190">خيطان</option>
                                                                <option value="191">مطار الكويت الدولي</option>
                                                                <option value="192">وسطى</option>
                                                                <option value="193">الراي</option>
                                                                <option value="194">العدان</option>
                                                                <option value="195">الرقعي</option>
                                                                <option value="196">القرين</option>
                                                                <option value="197">مطار  الشيخ سعد</option>
                                                                <option value="198">القصور</option>
                                                                <option value="199">صباح السالم</option>
                                                                <option value="200">مبارك الكبير</option>
                                                                <option value="201">الاحمدي</option>
                                                                <option value="202">ابو الحصاني</option>
                                                                <option value="203">الرقة</option>
                                                                <option value="204">ابو فطيرة</option>
                                                                <option value="205">المسايل</option>
                                                                <option value="206">الزور</option>
                                                                <option value="207">فنيطيس</option>
                                                                <option value="208">الصباحية</option>
                                                                <option value="209">المسيلة</option>
                                                                <option value="210">صباح الاحمد</option>
                                                                <option value="211">صبحان الصناعية</option>
                                                                <option value="212">الظهر</option>
                                                                <option value="213">جنوب وسطى</option>
                                                                <option value="214">الفحيحيل</option>
                                                                <option value="215">الفنطاس</option>
                                                                <option value="216">المنقف</option>
                                                                <option value="217">غرب ابو فطيرة الحرفية</option>
                                                                <option value="218">أبو حليفة</option>
                                                                <option value="219">المهبولة</option>
                                                                <option value="220">جابر العلي</option>
                                                                <option value="221">علي الصباح السالم</option>
                                                                <option value="222">فهد الاحمد</option>
                                                                <option value="223">هدية</option>
                                                                <option value="224">الجليعة</option>
                                                                <option value="225">الجابرية</option>
                                                                <option value="226">الخيران</option>
                                                                <option value="227">النويصب</option>
                                                                <option value="228">الوفرة</option>
                                                                <option value="229">بنيدر</option>
                                                                <option value="230">الرميثية</option>
                                                                <option value="231">العقيلة</option>
                                                                <option value="232">الضباعية</option>
                                                                <option value="233">الزهراء</option>
                                                                <option value="234">شاليهات ميناء عبدالله</option>
                                                                <option value="235">الشعيبة قطعة 1</option>
                                                                <option value="236">السالمية</option>
                                                                <option value="237">الشعيبة الصناعية الغربية</option>
                                                                <option value="238">السلام</option>
                                                                <option value="239">الشعب</option>
                                                                <option value="240">بيان</option>
                                                                <option value="241">حطين</option>
                                                                <option value="242">حولي</option>
                                                                <option value="243">الخالدية</option>
                                                                <option value="244">بنيد القار</option>
                                                                <option value="245">منطقة الحرة</option>
                                                                <option value="246">الدسمة</option>
                                                                <option value="247">الدعية</option>
                                                                <option value="248">سلوى</option>
                                                                <option value="249">مشرف</option>
                                                                <option value="250">دسمان</option>
                                                                <option value="251">البدع</option>
                                                                <option value="252">غرناطة</option>
                                                                <option value="253">الصديق</option>
                                                                <option value="254">الروضة</option>
                                                                <option value="255">انجفه</option>
                                                                <option value="256">السرة</option>
                                                                <option value="257">ميدان حولي</option>
                                                                <option value="258">الشامية</option>
                                                                <option value="259">مبارك العبدالله</option>
                                                                <option value="260">الشويخ</option>
                                                                <option value="261">الصليبيخات</option>
                                                                <option value="262">العديلية</option>
                                                                <option value="263">الفيحاء</option>
                                                                <option value="264">الشهداء</option>
                                                                <option value="265">جابر الاحمد</option>
                                                                <option value="266">القادسية</option>
                                                                <option value="267">القيروان</option>
                                                                <option value="268">الكويت</option>
                                                                <option value="269">قبلة</option>
                                                                <option value="270">المنصورية</option>
                                                                <option value="271">النزهة</option>
                                                                <option value="272">اليرموك</option>
                                                                <option value="273">شرق</option>
                                                                <option value="274">ضاحية عبد الله السالم</option>
                                                                <option value="275">قرطبة</option>
                                                                <option value="276">كيفان</option>
                                                                <option value="277">المرقاب</option>
                                                                <option value="278">النهضة</option>
                                                                <option value="279">شمال غرب الصليبيخات</option>
                                                                <option value="280">الصالحية</option>
                                                                <option value="281">شويخ الادارية</option>
                                                                <option value="282">الشويخ الصناعية</option>
                                                                <option value="283">الشويخ الصناعية 1</option>
                                                                <option value="284">الشويخ الصناعية 2</option>
                                                                <option value="285">الشويخ الصناعية 3</option>
                                                                <option value="286">سوق المباركية</option>
                                                                <option value="287">الصباح الطبية</option>
</select>
}
export default Area;