export const ar = {
    "home": "الصفحه الرئيسيه",
    "products": "المنتجات",
    "categories": "الأقسام",
    "about-us": "من نحن",
    "quick_links": "روابط سريعة",
    "Shop By Category": "تسوق حسب القسم",
    "View All": "عرض الكل",
    "Explore All": "استكشاف الكل",
    "Explore": "استكشف",
    "Feature Products": "المنتجات المميزة",
    "QUALITY": "الجودة التي يقدمها لك MASTER HN",
    "Best Selling Products": "أفضل المنتجات مبيعا",
    "DOWNLOAD MASTER HN": "تحميل Master HN",
    "Style Up Your Looks": "ارتقي بمظهرك",
}