export const ar = {
    "home": "الصفحه الرئيسيه",
    "products": "المنتجات",
    "categories": "الأقسام",
    "about-us": "من نحن",
    "quick_links": "روابط سريعة",
    "Shop By Category": "تسوق حسب القسم",
    "View All": "عرض الكل",
    "Explore All": "استكشاف الكل",
    "Explore": "استكشف",
    "Feature Products": "المنتجات المميزة",
    "QUALITY": "الجودة التي يقدمها لك MASTER HN",
    "Best Selling Products": "أفضل المنتجات مبيعا",
    "DOWNLOAD MASTER HN": "تحميل Master HN",
    "Style Up Your Looks": "صمم مطبخك",
    "All Rights": "كل الحقوق محفوظة",
    "Hasan Al Naser": "حسن الناصر",
    "Powered By": "مدعوم من",
    "Total Price": "السعر الإجمالي",
    "Continue": "متابعة",
    "Your Cart is Empty": "عربة التسوق فارغة",
    "KWD": "دينار كويتي",
    "Download Pdf": "تحميل الملف",
    "Style Up": "صمم",
    "Add To Cart": "أضف إلى السلة",
    "contact": "اتصل بنا",
    "Name": "الإسم",
    "Email": "البريد الإلكتروني",
    "Phone": "رقم الموبايل",
    "Message": "الرسالة",
    "CONTACT US ON WHATSAPP": "تواصل معنا عبر واتساب",
    "GET IN TOUCH": "ابق على تواصل",
    "Product": "المنتج",
    "Price": "السعر",
    "Quantity": "الكمية",
    "Total": "الإجمالي",
    "Sub Total": "المجموع الفرعي",
    "Payment Details": "تفاصيل الدفع",
    "Proceed": "هل ترغب في المتابعة لإتمام الطلب كـ",
    "Login": "تسجيل الدخول",
    "Continue as a Guest": "المتابعة كزائر",
    "Login Into Your Account": "تسجيل الدخول إلى حسابك",
    "Create New Account": "إنشاء حساب جديد",
    "Password": "الرقم السري",
    "Don't Have Account": "ليس لديك حساب",
    "Sign Up": "التسجيل",
    "Have Account": "لديك حساب",
}