export const en = {
    "home": "Home",
    "products": "Products",
    "categories": "Categories",
    "about-us": "About Us",
    "quick_links": "Quick Links",
    "Shop By Category": "Shop By Category",
    "View All": "View All",
    "Explore All": "Explore All",
    "Explore": "Explore",
    "Feature Products": "Feature Products",
    "QUALITY": "QUALITY BROUGHT TO YOU BY MASTER HN",
    "Best Selling Products": "Best Selling Products",
    "DOWNLOAD MASTER HN": "DOWNLOAD MASTER HN",
    "Style Up Your Looks": "Style Up Your Looks",
    "All Rights": "All Rights reserved",
    "Hasan Al Naser": "Hasan Al Naser",
    "Powered By": "Powered By",
    "Total Price": "Total Price",
    "Continue": "Continue",
    "Your Cart is Empty": "Your Cart is Empty",
    "KWD": "KWD",
    "Download Pdf": "Download Pdf",
    "Style Up": "Style Up",
    "Add To Cart": "Add To Cart",
    "contact": "Contact",
    "Name": "Name",
    "Email": "Email",
    "Phone": "Phone",
    "Message": "Message",
    "CONTACT US ON WHATSAPP": "CONTACT US ON WHATSAPP",
    "GET IN TOUCH": "GET IN TOUCH",
    "Product": "Product",
    "Price": "Price",
    "Quantity": "Quantity",
    "Total": "Total",
    "Sub Total": "Sub Total",
    "Payment Details": "Payment Details",
    "Proceed": "Do You Want To Proceed To Checkout As",
    "Login": "Login",
    "Continue as a Guest": "Continue as a Guest",
    "Login Into Your Account": "Login Into Your Account",
    "Create New Account": "Create New Account",
    "Password": "Password",
    "Don't Have Account": "Don't Have Account",
    "Sign Up": "Sign Up",
    "Have Account": "Have Account",
}