export const en = {
    "home": "Home",
    "products": "Products",
    "categories": "Categories",
    "about-us": "About Us",
    "quick_links": "Quick Links",
    "Shop By Category": "Shop By Category",
    "View All": "View All",
    "Explore All": "Explore All",
    "Explore": "Explore",
    "Feature Products": "Feature Products",
    "QUALITY": "QUALITY BROUGHT TO YOU BY MASTER HN",
    "Best Selling Products": "Best Selling Products",
    "DOWNLOAD MASTER HN": "DOWNLOAD MASTER HN",
    "Style Up Your Looks": "Style Up Your Looks",
}